//! Throwaway smoke test against real docx/pdf files generated by macOS tools.
//! Run manually: REALDOC_DIR=... cargo test --test realdoc_smoke -- --nocapture

use codebase_notebook_lib::domain::services::SourceScanner;
use codebase_notebook_lib::infrastructure::indexing::scanner::FsSourceScanner;

#[test]
fn real_word_and_pdf_files_extract_text() {
    let Ok(dir) = std::env::var("REALDOC_DIR") else {
        eprintln!("REALDOC_DIR not set; skipping");
        return;
    };
    let files = FsSourceScanner.scan(&dir).unwrap();
    for f in &files {
        eprintln!("== {} ({}) ==\n{}", f.rel_path, f.language, f.content);
    }
    let docx = files.iter().find(|f| f.rel_path.ends_with(".docx")).unwrap();
    assert!(docx.content.contains("Quarterly revenue"));
    let pdf = files.iter().find(|f| f.rel_path.ends_with(".pdf")).unwrap();
    assert!(pdf.content.contains("billing pipeline"));
}
